name: Label AI-Assisted Percentage

permissions:
  issues: write
  pull-requests: write

on:
  pull_request:
    types: [opened, edited]

jobs:
  assign-ai-label:
    runs-on: ubuntu-latest

    steps:
      - name: Calculate & apply AI-Assisted label
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // core, github & context are already available
            const { payload } = context;
            const pr = payload.pull_request || {};
            const body = pr.body || '';

            const { owner, repo } = context.repo;
            const issue_number = context.issue.number;

            // build a link to this workflow run
            const serverUrl = process.env.GITHUB_SERVER_URL || 'https://github.com';
            const runId     = process.env.GITHUB_RUN_ID;
            const runUrl    = `${serverUrl}/${owner}/${repo}/actions/runs/${runId}`;

            // 1) Extract manual rate
            const match = body.match(/Manual Engineering rate:\s*(\d{1,3})%/i);
            if (!match) {
              await github.rest.issues.createComment({
                owner, repo, issue_number,
                body: `⚠️ **Error:** Could not find \`Manual Engineering rate: x%\` in the description. Please add a line like \`Manual Engineering rate: 30%\`.\n\nSee run details: ${runUrl}`
              });
              core.setFailed('Manual Engineering rate not found.');
              return;
            }

            const manual = parseInt(match[1], 10);
            if (manual < 0 || manual > 100) {
              await github.rest.issues.createComment({
                owner, repo, issue_number,
                body: `⚠️ **Error:** Manual Engineering rate \`${manual}%\` is invalid. It must be between 0 and 100.\n\nYou provided: ${manual}%\nSee run details: ${runUrl}`
              });
              core.setFailed('Manual Engineering rate out of range.');
              return;
            }

            // ... rest remains unchanged ...
            // 2) Compute & round AI rate
            const rawAi = 100 - manual;
            let aiBucket = Math.round(rawAi / 10) * 10;
            if (aiBucket < 10) aiBucket = 10;
            if (aiBucket > 100) aiBucket = 100;
            const newLabel = `AI-Assisted: ${aiBucket}%`;

            // 3) Remove old labels
            for (const lbl of pr.labels.map(l => l.name)) {
              if (/^AI-Assisted:\s*\d+%$/.test(lbl) && lbl !== newLabel) {
                await github.rest.issues.removeLabel({ owner, repo, issue_number, name: lbl });
              }
            }

            // 4) Verify label exists
            try {
              await github.rest.issues.getLabel({ owner, repo, name: newLabel });
            } catch {
              await github.rest.issues.createComment({
                owner, repo, issue_number,
                body: `⚠️ **Error:** Required label \`${newLabel}\` does not exist. Please create it first.\n\nSee run details: ${runUrl}`
              });
              core.setFailed(`Label ${newLabel} not found.`);
              return;
            }

            // 5) Apply the correct label
            await github.rest.issues.addLabels({
              owner, repo, issue_number,
              labels: [newLabel]
            });
