name: Label AI-Assisted Percentage

permissions:
  issues: write
  pull-requests: write

on:
  pull_request:
    types: [opened, edited]

jobs:
  assign-ai-label:
    runs-on: ubuntu-latest

    steps:
      - name: Calculate & apply AI-Assisted label
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // core, github & context are already available
            const { payload } = context;
            const pr = payload.pull_request || {};
            const body = pr.body || '';

            const { owner, repo } = context.repo;
            const issue_number = context.issue.number;

            // 1) Extract manual rate
            const match = body.match(/Manual Engineering rate:\s*(\d{1,3})%/i);
            if (!match) {
              core.setFailed('❌ Parsing error: no `Manual Engineering rate: x%` found in PR description.');
              return;
            }

            // 2) Validate range
            const manual = parseInt(match[1], 10);
            if (manual < 0 || manual > 100 || isNaN(manual)) {
              core.setFailed(`❌ Invalid Manual Engineering rate: \`${manual}%\` (must be between 0 and 100).`);
              return;
            }

            // 3) Compute AI rate and snap to 10% buckets
            const rawAi = 100 - manual;
            let aiBucket = Math.round(rawAi / 10) * 10;
            if (aiBucket < 10) aiBucket = 10;
            if (aiBucket > 100) aiBucket = 100;
            const newLabel = `AI-Assisted: ${aiBucket}%`;

            // 4) Remove any old AI-Assisted:*% labels
            for (const lbl of pr.labels.map(l => l.name)) {
              if (/^AI-Assisted:\s*\d+%$/.test(lbl) && lbl !== newLabel) {
                await github.rest.issues.removeLabel({ owner, repo, issue_number, name: lbl });
              }
            }

            // 5) Verify that the target label already exists
            try {
              await github.rest.issues.getLabel({ owner, repo, name: newLabel });
            } catch {
              core.setFailed(`❌ Missing label: \`${newLabel}\` does not exist in this repository.`);
              return;
            }

            // 6) Apply the correct label
            await github.rest.issues.addLabels({
              owner,
              repo,
              issue_number,
              labels: [newLabel]
            });
